### ISSUE TITLE
Installation on macOS?

### ISSUE THREAD

**Issue by ItsPugle** [theimgguru/tigcap#4]
Does anyone know how you can install this on macOS?

**Comment by Mstrodl** [comment]
@ItsPugle `yarn install` and then `yarn start`

**Comment by ItsPugle** [comment]
@Mstrodl What's the package name? Sorry - I'm not familiar with `yarn` - only Homebrew!

**Comment by Mstrodl** [comment]
@ItsPugle Install nodejs and then you can `sudo npm i -g yarn`

**Comment by ItsPugle** [comment]
@Mstrodl - I've already installed `yarn`, I just don't know how to install tigcap using yarn.

**Comment by Mstrodl** [comment]
@ItsPugle Like this:
```bash
# Clone the repo
git clone https://github.com/theimgguru/tigcap.git
# Install deps
yarn install
# Run tigcap
yarn start
```
