### ISSUE TITLE
TIG no longer works

### ISSUE THREAD

**Issue by Kelwing** [theimgguru/tigcap#7]
theimgguru merged with a few other image hosting services, most notably bread.moe, to form a new service called [Kuvien](https://kuvien.io).  There has been talk of an interest in creating a custom uploader for kuvien, maybe just add support to tigcap?

**Comment by Mstrodl** [comment]
@Kelwing Sure assuming you can give a quick explanation of the upload enpoint

**Comment by Kelwing** [comment]
Uploads take the form of POST requests to https://api.kuvien.io/image/upload
An API key is required from the user, and must be sent in the x-app-key header.
The body of the post should be multipart/form-data with "file" as the field name for the file data.

**Comment by Mstrodl** [comment]
@Kelwing Thanks!

**Comment by Mstrodl** [comment]
@Kelwing Actually, can you give a sample response from that endpoint? Is it json or is it just a url or..?

**Comment by Mstrodl** [comment]
Ah, so it's the same as the old one. Thanks!
